// let mydate=new Date();
// console.log(mydate.toString())
// console.log(mydate.toLocaleString())
// console.log(mydate.toDateString())


// let mycreatedate=new Date(2023,0,22);
// console.log(mycreatedate.toString());
// console.log(mycreatedate.toDateString())


// let mycreatedate=new Date(2023,0,23);
// console.log(mycreatedate.toString());
// console.log(mycreatedate.toDateString())

// let mycreatedate=new Date(2023,0,22,0,23);
// // console.log(mycreatedate.toString())
// // console.log(mycreatedate.toDateString())
// console.log(mycreatedate.toLocaleString())

// let mycreatedate=new Date("01-14-2023");
// console.log(mycreatedate.toLocaleString())

// let mycreatedate=new Date("2023-01-14");
// // console.log(mycreatedate.toLocaleString())

// // let myTimeStamp=new Date.now;
// console.log(mycreatedate.getTime());
// console.log(Math.floor(Date.now()/1000))  //convert the milliseconds

let newdate=new Date();
console.log(newdate.getMonth())








